### ISSUE TITLE
Config file detection

### ISSUE THREAD

**Issue by broamski** [broamski/botomfa#2]
If .boto is not present or empty the following exception is thrown:

```
Temporary credentials are missing grabbing them again
Traceback (most recent call last):
  File "/usr/bin/botomfa", line 22, in <module>
    botomfa.run(duration)
  File "build/bdist.linux-x86_64/egg/botomfa.py", line 103, in run
  File "build/bdist.linux-x86_64/egg/botomfa.py", line 29, in get_sts
  File "/usr/lib64/python2.7/os.py", line 473, in __setitem__
    putenv(key, item)
TypeError: must be string, not None
```

**Comment by broamski** [comment]
g2g
